name: CI

on:
  push:
    branches:
      - master
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  test:
    name: Pester Tests
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      # Pester is installed by default
      - name: Run Pester Tests
        run: Invoke-Pester -Path .\tests -OutputFile .\testresults.xml -OutputFormat NUnitXml
      - name: Upload Unit Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Unit Test Results
          path: ./tests/out/testResults.xml
  publish-test-results:
    name: "Publish Unit Tests Results"
    needs: test
    runs-on: ubuntu-latest
    # the test job might be skipped, we don't need to run this job then
    if: success() || failure()

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: artifacts/**/*.xml